package oleg.sopilnyak.xml;

import oleg.sopilnyak.util.AtomElementService;
import org.jdom2.JDOMException;
import org.junit.Test;

import java.io.IOException;
import java.util.List;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;

public class AtomServiceTest {
    private final String data = "<NewDataSet>\n" +
            "  <Table>\n" +
            "    <ElementName>Actinium</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Aluminium</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Americium</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Antimony</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Argon</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Arsenic</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Astatine</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Barium</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Berkelium</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Beryllium</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Bismuth</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Bohrium</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Boron</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Bromine</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Cadmium</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Calcium</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Californium</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Carbon</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Cerium</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Cesium</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Chlorine</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Chromium</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Cobalt</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Copper</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Curcigtonium</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Curium</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Dysprosium</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Einsteinium</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Erbium</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Europium</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Fermium</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Flourine</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Francium</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Gadolinium</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Gallium</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Germanium</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Gold</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Hafnium</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Hahnium</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Hassium</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Helium</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Holmium</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Hydrogen</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Indium</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Iodine</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Iridium</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Iron</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Krypton</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Lanthanum</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Lawrencium</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Lead</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Lithium</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Lutetium</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Magnesium</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Manganese</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Meitnerium</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Mendelevium</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Mercury</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Molybdenum</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Neodymium</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Neon</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Neptunium</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Nickel</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Niobium</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Nitrogen</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Nobelium</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Osmium</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Oxygen</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Palladium</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Phosphorous</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Platinum</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Plutonium</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Polonium</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Potassium</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Praseodymium</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Promethium</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Protactinium</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Radium</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Radon</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Rhenium</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Rhodium</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Rubidium</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Ruthenium</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Samarium</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Scandium</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Seaborgium</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Selenium</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Silicon</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Silver</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Sodium</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Strontium</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Sulphur</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Tantalum</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Technetium</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Telurium</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Terbium</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Thallium</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Thorium</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Thulium</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Tin</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Titanium</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Tungsten</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Ununbium</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Ununnilium</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Unununium</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Uranium</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Vanadium</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Xenon</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Ytterbium</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Yttrium</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Zinc</ElementName>\n" +
            "  </Table>\n" +
            "  <Table>\n" +
            "    <ElementName>Zirconium</ElementName>\n" +
            "  </Table>\n" +
            "</NewDataSet>";
    @Test
    public void testAtoms() throws JDOMException, IOException {
        List<String> atoms = AtomElementService.atomElements(data);
        assertNotNull(atoms);
    }
    @Test
    public void testAtomParameter() throws Exception{
        String value = AtomElementService.atomParameter(data, "ElementName");
        assertNotNull(value);
        assertEquals("Actinium", value);
    }
}
